$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: docker-basic 
endpoint_name: endpoint-name
code_configuration: 
  code: "."
  scoring_script: score.py
environment:
  image: container_registry.azurecr.io/docker-conda:latest
  conda_file : /docker_storage/conda.yml 
instance_type: Standard_F2s_v2
instance_count: 1